<a href="https://colab.research.google.com/github/soujanya-vattikolla/PyTorch/blob/main/01_Assignmenttensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Few basic functions in Pytorch

PyTorch is an open source machine learning library based on the Torch library used for applications like image recognition or text recognition using deep learning.

1. torch.randn()
2. torch.sort()
3. torch.pow()
4. torch.round()
5. torch.det()

In [ ]:
# Import torch and other required modules
import torch as th

### Function 1 -  torch.randn()

torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)

Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
The shape of the tensor is defined by the variable argument size.

In [ ]:
# Example 1 
x_randn = th.randn(4,3)
print('X: ',x_randn)

X:  tensor([[ 0.1299, -0.9182, -0.6502],
        [-1.0658,  0.8459,  1.8579],
        [-1.0836, -0.1551,  0.8129],
        [-0.2247, -1.5154, -0.7566]])


In the above example created a tensor having 4 Rows and 3 Coulumn with 12 random elements.

In [ ]:
# Example 2
y_randn = th.randn(2,4,3)
print('Y: \n',y_randn)

Y: 
 tensor([[[-0.5828, -1.3263,  0.6279],
         [ 0.6594, -0.7537, -1.0471],
         [ 0.7428,  0.1563,  0.5579],
         [ 0.1383, -1.5144, -0.2578]],

        [[-0.6065, -0.1259, -0.8788],
         [-0.1935, -1.2056, -0.8559],
         [-0.0996,  0.4268, -0.0886],
         [-0.1496, -0.5486,  1.1226]]])


In the above example created a 3-D tensor having 2 subtensors of 4 Rows and 3 Coloumn.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z_randn = th.randn()
z_randn

TypeError: ignored

The above example produces an error because randn() function requires at least one positional arguments: "size" without which all the other arguments will not work too.


### Function 2 torch.sort()

torch.sort(input, dim=-1, descending=False, out=None) -> (Tensor, LongTensor)

This function sorts the elements of the input tensor along a given dimension in ascending order by value.

In [ ]:
# Example 1
a_sort = th.randn(5,10)
sortedA, indicesA = th.sort(a_sort, descending=False)
print('Sorted tensor elements in Ascending order: \n',sortedA)

Sorted tensor elements in Ascending order: 
 tensor([[-2.5962, -1.1733, -0.8126, -0.3908, -0.2917, -0.2005,  0.2083,  0.2868,
          0.7272,  1.0371],
        [-2.0168, -1.2161, -1.1285, -1.1197, -1.0163, -0.5888,  0.5917,  0.6207,
          0.8758,  0.9538],
        [-2.0913, -0.1753, -0.1334,  0.0497,  0.7715,  1.3295,  1.6612,  2.2265,
          2.3269,  2.7857],
        [-0.8191, -0.5628, -0.0488,  0.2246,  0.3173,  0.4047,  0.5267,  0.6207,
          0.8157,  0.8394],
        [-1.4112, -1.2232, -0.8918, -0.0757,  0.1951,  0.2853,  0.5667,  0.8571,
          0.9196,  1.1943]])


In the above example with the help of torch.sort() sorted the elements of the 5,10 matrix in ascending order row wise.

In [ ]:
# Example 2 
b_sort = th.randn(10)
sortedb, indicesb = th.sort(b_sort,descending=False)
print('Sorted Elements: \n',sortedb)
print('Indices of the elements according to their values: \n',indicesb)


Sorted Elements: 
 tensor([-0.6713, -0.5784, -0.5717, -0.4200, -0.4087,  0.0535,  0.2473,  0.3507,
         1.0553,  1.3482])
Indices of the elements according to their values: 
 tensor([1, 6, 5, 3, 4, 2, 7, 0, 9, 8])


In the above example sorted a 1D tensor with the help of torch.sort() function.

In [ ]:
# Example 3 
sortedc = th.sort(c)
print(sortedc)

NameError: ignored

The above example breaks because for the torch.sort() functions to operate, an argument which is previsoly present has to be provided.

### Function 3 - torch.pow()

torch.pow(input, exponent, out=None)

This function takes the power of each element in input with exponent and returns a tensor with the result. exponent can be either a single float number or a tensor with the same number of elements as input.

In [ ]:
# Example 1
x_randn = th.randn(5)
print('Value of P: \n',x_randn)
pow_values = th.pow(x_randn,2)
print('Value of x after applying .pow function: \n',pow_values)


Value of P: 
 tensor([-0.3977, -0.7607, -0.2513,  0.5362,  0.7787])
Value of P after applying .pow function: 
 tensor([0.1581, 0.5786, 0.0632, 0.2875, 0.6064])


In the above example squared each element of the 1D tensor.

In [ ]:
# Example 2
q_randn = th.randn(3,4)
print('Value of q: \n',q_randn)
pow_values = th.pow(q_randn,-2)
print('Elements of q  after dividing each element by itself raised to the power of 2: \n',pow_values)

Value of q: 
 tensor([[ 0.5749,  0.4173, -0.4507,  0.3208],
        [ 0.1783,  0.0922,  0.3365, -0.4709],
        [ 1.9226, -1.3706,  0.3454, -0.2219]])
Elements of q after dividing each element by itself raised to the power of 2: 
 tensor([[  3.0261,   5.7437,   4.9236,   9.7174],
        [ 31.4442, 117.7169,   8.8329,   4.5098],
        [  0.2705,   0.5323,   8.3811,  20.3116]])


In the above example divided each element by itself raised to the power of 2.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
r_randn = th.randn(4,5)
print('Value of r: \n',r_randn)
r_pow = th.pow(-0.98)

Value of r: 
 tensor([[ 1.4682, -0.0932,  0.1669, -1.2628, -0.0266],
        [-2.7245, -1.6710,  1.0727,  0.9330, -0.8266],
        [-0.3095,  1.8426,  0.2650, -0.0924,  0.1694],
        [ 0.8069,  0.2475, -1.1516,  1.8029, -1.2293]])


TypeError: ignored

The above example breaks beacuse the torch.pow() function requires an argument of the type matrix,number,Tensor etc to process them to that power.

### Function 4 - torch.round()

torch.round(input, out=None)

Returns a new tensor with each of the elements of input rounded to the closest integer.

In [ ]:
# Example 1 
m_randn = th.randn(10)*10
print('m: \n',m_randn)
m_round = th.round(m_randn)
print('After rounding: \n',m_round)

m: 
 tensor([-12.2200,  -5.3102,  22.0502,   6.1078,  -1.2981,  -5.1620,   8.6544,
         -7.0037,   4.7211,   5.8143])
After rounding: 
 tensor([-12.,  -5.,  22.,   6.,  -1.,  -5.,   9.,  -7.,   5.,   6.])


In the above example rounded of every element of a 1D matrixm to its closest integer

In [ ]:
# Example 2 
n_randn = th.randn(5,5)*10
print('n: \n',n_randn)
n_round = th.round(n_randn)
print('After rounding: \n',n_round)

n: 
 tensor([[-20.9472,  19.9217,   5.8674, -16.6392,   5.0424],
        [-13.5306, -13.1298,  10.7305,  -5.6534,   8.6863],
        [  2.5831,  -0.9806,  -4.2670,   1.8648,  23.6868],
        [ -5.3758,  14.1453,  -3.1910, -17.5154,  10.1422],
        [  2.1253,  -6.0117, -11.9144, -20.3586, -17.7449]])
After rounding: 
 tensor([[-21.,  20.,   6., -17.,   5.],
        [-14., -13.,  11.,  -6.,   9.],
        [  3.,  -1.,  -4.,   2.,  24.],
        [ -5.,  14.,  -3., -18.,  10.],
        [  2.,  -6., -12., -20., -18.]])


In the above example rounded all elements of a 2D matrix n to its nearest integer value.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
import numpy as np
o_rand = np.random.rand(5,3)
print('o: \n',o_rand)
o_round = th.round(o_rand)

o: 
 [[6.10299962e-01 1.22991195e-01 7.99393025e-01]
 [2.25696565e-01 7.93051577e-01 3.12795898e-01]
 [1.42782713e-01 1.48187371e-01 1.86783141e-01]
 [5.83238692e-01 3.52520062e-01 2.12293424e-02]
 [1.52943877e-01 3.71550248e-01 6.03500042e-04]]


TypeError: ignored

The above example breaks because the function torch.round() requires its input to be of the type tensor but the argument to it was provided of the type numpy.ndarray

### Function 5 - torch.det()

torch.det(input) → Tensor

Calculates determinant of a square matrix or batches of square matrices.

In [ ]:
# Example 1 - working
g_det = th.randn(5,5)
print('g: \n',g_det)
print('Determinant of g: \n',th.det(g_det))

g: 
 tensor([[ 0.2617, -1.3215,  1.8579,  0.7513, -0.1217],
        [-1.5749,  0.9443, -1.3750, -0.4767, -1.0985],
        [-1.6740,  0.1563,  1.6821, -0.9209, -0.4555],
        [ 0.2936, -0.8855,  0.0113,  0.1522, -0.8913],
        [ 0.3268, -0.3660,  1.5177, -0.5314, -1.0224]])
Determinant of g: 
 tensor(-5.2219)


In the above example calculated the determinant of g matrix.

In [ ]:
# Example 2 - working
h_det = th.randn(3,5,5)
print('h: \n',h_det)
print('Determinant of h: \n',th.det(h_det))

h: 
 tensor([[[ 0.8791,  0.2284, -0.0107, -0.4914, -0.1269],
         [-0.0241, -0.2817,  1.7605, -0.9118, -1.2149],
         [ 0.9761,  1.1361, -0.3250,  1.0504, -1.3700],
         [-0.1689, -0.7956, -1.2309,  0.3865, -0.4375],
         [-1.1455,  2.9759, -2.6746, -0.1407,  1.0568]],

        [[-0.0940,  0.1926,  1.6205,  0.2430, -0.6728],
         [ 0.8446,  0.4767,  0.5010, -1.8106,  1.0331],
         [-0.0576, -0.2928, -0.8433,  0.9258, -0.4223],
         [-0.9858,  0.6822, -0.6550,  1.9450, -1.1169],
         [ 0.8031, -1.5200, -0.0335,  0.0392,  0.2291]],

        [[-0.2684,  0.4801,  0.6369,  0.0797, -0.9501],
         [-1.2863, -1.0077,  0.1728, -0.3896, -1.9315],
         [-0.8581, -1.0500,  1.4344, -0.8564, -0.8443],
         [-0.1503,  2.2748, -1.2517,  1.3491, -0.7643],
         [-0.2325,  0.3962, -0.2546, -0.3563,  0.0615]]])
Determinant of h: 
 tensor([20.5267, -0.4800,  1.3341])


In the above example the determinant of 3 2D matrix with the help of torch.det() function.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
i_det = th.randn(10)
print('i: \n',i_det)
print('Determinant of i: \n',th.det(i_det))

i: 
 tensor([-0.3562, -0.1495, -0.6797, -0.8168, -0.3851,  0.4562,  0.5058,  2.6212,
         0.9224,  1.4842])


RuntimeError: ignored

The above example fails because determinant can only be found for matrices greater than 1D.